apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-service
  labels:
    app: usermgmt-webapp
spec:
  type: NodePort #ClusterIp or Loadbalancer
  selector:
    app: usermgmt-webapp
  ports:
    targetPort: 8080
