apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp
  labels:
    app: usermgmt-webapp
spec:
  type: NodePort #ClusterIp or Loadbalancer
  selector:
    app: usermgmt-webapp
  ports:
    - port: 8080
  